(define (problem sokobanP2-1)
	(:domain sokoban-domain)
	(:objects theBot theBox c1 c2 c3 c4 c5 c6 c7 c8 c9 c10 c11 c12 c13)
	(:init (bot theBot)
	       (box theBox)
	       (cell c1) (cell c2) (cell c3) (cell c4) 
	       (cell c5) (cell c6) (cell c7) (cell c8)
	       (cell c9) (cell c10) (cell c11) (cell c12) (cell c13)
	       (left-right c1 c2)
	       (left-right c4 c5)
	       (left-right c5 c6)
	       (left-right c6 c7)
	       (left-right c8 c9)
	       (left-right c9 c10)
	       (left-right c10 c11)
	       (left-right c12 c13)
	       (onTop c2 c3)
	       (onTop c3 c5)
	       (onTop c5 c9)
	       (onTop c9 c13)
	       (onTop c4 c8)
	       (onTop c8 c12)
	       (onTop c6 c10)
	       (onTop c7 c11)
	       (empty c1) (empty c2) (empty c4) (empty c5)
	       (empty c6) (empty c7) (empty c8) (empty c9)
	       (empty c11) (empty c12) (empty c13)
	       (at theBot c3)
	       (at theBox c10)
	 )
	 (:goal (at theBox c2)))
